# https://taskfile.dev

version: '3'

vars:
  CLI: cli
  SRV: srv
  CAPTURE_FILE: capture.pcap
  SERVER_ADDR: 127.0.0.1
  SERVER_PORT: 12345

tasks:
  default:
    cmds:
      - go build -o {{.CLI}} client/main.go
      - go build -o {{.SRV}} server/main.go
      - ./{{.SRV}} &
      - sleep 0.1s
      - ./{{.CLI}} &
      - pkill {{.SRV}} || true
    silent: true
